### Camera Calibration

The calibration of cameras consists is an essential task in computer vision. I cannot stress enough how important it is in any business involving distance estimation, in particular in this era where we are striving for autonomous vehicles.

Nowadays, modern vehicles are equipped with cameras and embed software dedicated to the safety of road users, that is us humans and other animals. Let us leave out the topic of LIDAR devices, which is out-of-scope of this book.

At some point, the embedded software will try to estimate the distance between the vehicle and any pedestrian in the camera field-of-view, which is a critical data for the safety of pedestrians.

To estimate the distance of pedestrians from the vehicle, we need to understand qualitatively and quantitatively how the images are formed in the camera. This constitutes the very first requirement for such computer vision systems.

    Qualitatively, we need to find a mathematical camera model that explains very the projection of 3D scene points in the image. Is the simple camera pinhole model sufficient to model the image formation? Or is there any lens distortion: can we find good continuous mathematical function that describes it? The camera model depends on how the camera lens is manufactured.

    Quantitatively, we need to estimate the parameters of the camera model, namely the focal length, the lens distortion parameters and so on.

There are two class of camera calibration approaches to estimate the camera parameters.

    The first class involves fiducial markers, the most prevalent one being the planar chessboard pattern. As annoying building a solid chessboard pattern may be, it is however the most reliable approach for industrial applications and even more so for the safety of people and animals.

    The second class involves no fiducial markers and will involve local image point features. The second class exploits beautiful mathematical objects devised in multiple view geometry. However it is a rather tricky approach and has many drawbacks: it will be less accurate than fiducial calibration approaches and is well investigated for the pinhole camera model mostly.

I will focus only chessboard-based camera calibration. 
