# Literature

Here is a review of existing methods.

```{r}
x <- 5  # radius of a circle
```

For a circle with the radius `r x`,
its area is `r pi * x^2`.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash}
echo "Hello Bash!"
```

```{Rcpp, cache=TRUE}

#include <iostream>
#include <utility>
#include <string>

#include <Rcpp.h>

// [[Rcpp::plugins(cpp17)]

// [[Rcpp::export]]
int fibonacci(int x)
{
  const auto [a, b] = std::make_pair(0, 1);
  if (x == 0 || x == 1)
    return x;
  return fibonacci(x-1) + fibonacci(x-2);
}

// // [[Rcpp::export]]
// Rcpp::String hello_me()
// {
//   return Rcpp::String("hello");
// }
```

```{r}
fibonacci(10L)
# hello_me()
```

```{python}
from matplotlib import pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np

# Two example plots
fig = plt.figure()
ax1 = fig.add_subplot(2,2,1)
ax2 = fig.add_subplot(2,2,2)

spacing = 0.5 # This can be your user specified spacing.
minorLocator = MultipleLocator(spacing)
ax1.plot(9 * np.random.rand(10))
# Set minor tick locations.
ax1.yaxis.set_minor_locator(minorLocator)
ax1.xaxis.set_minor_locator(minorLocator)
# Set grid to use minor tick locations.
ax1.grid(which = 'minor')

spacing = 1
minorLocator = MultipleLocator(spacing)
ax2.plot(9 * np.random.rand(10))
# Set minor tick locations.
ax2.yaxis.set_minor_locator(minorLocator)
ax2.xaxis.set_minor_locator(minorLocator)
# Set grid to use minor tick locations.
ax2.grid(which = 'minor')
plt.show()
```

