FROM emscripten/emsdk:3.1.46

MAINTAINER "Odd Kiva"

# Set up my development workspace.
WORKDIR /workspace/hasten

# C++ toolchain, libraries and tools.
RUN apt-get update -y && apt-get install -y \
  ccache \
  ninja-build

