## Vanishing Point

In projective geometry, the projection of 3D lines in the camera film plane are
still line segments. However, the perspective projection does not preserve the
parallelism.

To make things clear in our mind, images are thus formed by some pinhole camera
model with calibration matrix $\mathbf{K}$.

One remarkable property in projective geometry is that the projection of 3D
parallel lines onto an image plane is a set of 2D lines that intersect
altogether into a unique point: the so-called *vanishing point*.

### Terminology

Let us recall a bit of terminology.

- Any 3D scene point $X$ that lies in a 3D semi-line originating from the camera
  center $O$ **projects** exactly on a unique point $\mathbf{u}$ in the image
  plane.

We also like to say the other way around, in 3D reconstruction:

- A point $\mathbf{u}$ in the image plane **backprojects** to a 3D semi-line or
  equivalently to the 3D ray vector $\mathbf{r}_\mathbf{u}$ that parameterizes
  this semi-line.

Now let us take it further.

- A 2D line segment $(\mathbf{a}, \mathbf{b})$ in the image plane backprojects to
  a 3D half-plane $(\mathbf{O}, \mathbf{r}_\mathbf{a}, \mathbf{r}_\mathbf{b})$
  where $\mathbf{r}_\mathbf{a}$ and $\mathbf{r}_\mathbf{b}$ are respectively the
  backprojected rays of the 2D image points $\mathbf{a}$ and $\mathbf{b}$.

- The half-plane $(\mathbf{O}, \mathbf{r}_\mathbf{a}, \mathbf{r}_\mathbf{b})$
  can be parameterized by its normal vector $\mathbf{\Pi}(\mathbf{a},
  \mathbf{b})$^[Let's omit the side of the half-plane for now, which can be
  retrieved a cheirality criterion], which we calculate as

  \begin{equation}
  \mathbf{\Pi}(\mathbf{a}, \mathbf{b}) =
    \mathbf{r}_\mathbf{a} \times \mathbf{r}_\mathbf{b}.
  \end{equation}

- Note that the backprojected rays are thus calculated as

  \begin{align*}
    \mathbf{r}_\mathbf{a} &= \mathbf{K}^{-1} \mathbf{a} \\
    %
    \mathbf{r}_\mathbf{b} &= \mathbf{K}^{-1} \mathbf{b}.
  \end{align*}

- Another way to calculate the plane normals is to use the normal vector
  $\mathbf{n}$ of the image line segment $(\mathbf{a}, \mathbf{b})$, and then:

  \begin{equation}
  \mathbf{\Pi}(\mathbf{a}, \mathbf{b}) =
    \mathbf{K}^T \mathbf{n}.
  \end{equation}

### Vanishing point

A vanishing point can be traced from two "parallel" 2D line segments $l_1$ and
$l_2$. These 2D line segments backproject to two 3D planes $\mathbf{\Pi}(l_1)$
and $\mathbf{\Pi}(l_2)$ that intersect at the camera center.

But also, because the intersection of two non parallel 3D planes must be a 3D
line in general, their intersection is calculated as the cross-product

  \begin{equation}
    \mathbf{\Pi}(l_1) \times \mathbf{\Pi}(l_2).
  \end{equation}

This cross-product is exactly the backprojected ray of the vanishing point.
Let's call it the vanishing ray.

As a side note:

- the dual representation of a 3D vector is the plane orthogonal to the
  vector itself;
- thus in particular, the dual representation of a vanishing ray is the plane
  orthogonal to the vanishing ray itself.

Finally, two vanishing points in the images are orthogonal if they backproject to two
orthogonal vectors. We can retrieve the third orthogonal ray by calculating the
cross-product of the two orthogonal vectors.

\begin{equation}
  \mathbf{\Pi}(l_3) = \mathbf{\Pi}(l_1) \times \mathbf{\Pi}(l_2).
\end{equation}

### Orthogonal Vanishing Point Detection

The detection of orthogonal vanishing point assumes that cameras are calibrated,
that is we understand how the images are formed and know the camera parameters.
We know not just the calibration matrix, but also its distortion model and its
distortion coefficients.

We are now able to derive an algorithm that can compute the reference frame of a
Manhattan world. If we use RANSAC where we draw minimal samples of 3 line
segments, we can infer the orientation of the camera with respect to the
Manhattan world frame.

This approach is described more in details in the paper [@BazinP:2012:iros].
Basically, the main idea is as follows. A good sample of 3 line segments is a sample
such that

- The first two image line segments are parallel and are used to construct a
  first vanishing point.
- The third line segment vanishes to a second vanishing point, which should be
  orthogonal to the first vanishing point.
- The third orthogonal vanishing point is obtained by cross-product.
In that case, the three orthogonal vanishing points are well supported by the
other line segments.
