\newcommand{\cA}{\mathcal{A}}
\newcommand{\cB}{\mathcal{B}}
\newcommand{\cC}{\mathcal{C}}
\newcommand{\cW}{\mathcal{W}}

# Reference Frames

:::fyi
In this section, I use *reference frame* and *coordinate system*
interchangeably.

This is inexact since a reference frame has a physical meaning and the
coordinate system is just a 3D mapping that quantifies object positions with
respect to a reference point.

On the other hand, it makes the explanation more natural so I prefer to keep the
text as it is. Now when I refer to the coordinate system, I do refer to the
Cartesian one. And of course, non-Cartesian coordinate systems such as the
cylindric one can also be used for any reference frame.
:::

Let us detail how we go from the camera coordinates $(O_\cC, \mathbf{i}_\cC,
\mathbf{j}_\cC,\mathbf{k}_\cC)$ to the world coordinates $(O_\cW,
\mathbf{i}_\cW, \mathbf{j}_\cW,\mathbf{k}_\cW)$. We assume the basis vectors are
*orthonormal* and *right-handed*, that is each vector has a magnitude equal to
$1$ and forms mutually a right angle between each of them.

\begin{align*}
  \mathbf{i} \times \mathbf{j} &= \mathbf{k} \\
  %
  \| i \| &= \| j \| = \| k \| = 1.
\end{align*}

Denote a 3D point by $M$ and suppose that we know its coordinates in the
camera coordinate system $(x_\cC, y_\cC, z_\cC)$. We can retrieve its
coordinates in the world coordinate system $(x_\cW, y_\cW, z_\cW)$ as
follows.

Let us start with Chasles' relation so that the world coordinates are expressed
as

\begin{equation}
  \overrightarrow{O_\cW M} = \overrightarrow{O_\cW O_\cC} +
                           \overrightarrow{O_\cC M}.
\end{equation}

The second term can be expressed with the camera coordinates

\begin{equation}
  \overrightarrow{O_\cW M} = \overrightarrow{O_\cW O_\cC} +
    x_\cC \mathbf{i}_\cC + y_\cC \mathbf{j}_\cC + z_\cC \mathbf{k}_\cC .
\end{equation}

Let us denote the camera axes w.r.t. the world coordinate system as
\begin{equation}
  \begin{array}{ccc}
  \mathbf{i}_\cC = \begin{bmatrix} i_{\cC1} \\ i_{\cC2} \\ i_{\cC3} \end{bmatrix},
  &
  \mathbf{j}_\cC = \begin{bmatrix} j_{\cC1} \\ j_{\cC2} \\ j_{\cC3} \end{bmatrix},
  &
  \mathbf{k}_\cC = \begin{bmatrix} k_{\cC1} \\ k_{\cC2} \\ k_{\cC3} \end{bmatrix}
  \end{array}
  .
\end{equation}

Reorganizing in matrix notation, the matrix-vector product becomes apparent:
\begin{equation}
  \begin{aligned}
  \overrightarrow{O_\cW M} &= \overrightarrow{O_\cW O_\cC} +
  x_\cC
  \begin{bmatrix}
    i_{\cC1} \\
    i_{\cC2} \\
    i_{\cC3}
  \end{bmatrix} +
  y_\cC
  \begin{bmatrix}
    j_{\cC1} \\
    j_{\cC2} \\
    j_{\cC3}
  \end{bmatrix} +
  z_\cC
  \begin{bmatrix}
    k_{\cC1} \\
    k_{\cC2} \\
    k_{\cC3}
  \end{bmatrix} \\
  %
  \overrightarrow{O_\cW M} &= \overrightarrow{O_\cW O_\cC} +
  \begin{bmatrix}
  i_{\cC1} & j_{\cC1} & k_{\cC1} \\
  i_{\cC2} & j_{\cC2} & k_{\cC2} \\
  i_{\cC3} & j_{\cC3} & k_{\cC3}
  \end{bmatrix}
  %
  \begin{bmatrix} x_\cC \\ y_\cC \\ z_\cC \end{bmatrix} \\
  %
  \overrightarrow{O_\cW M} &= \overrightarrow{O_\cW O_\cC} +
  \left[ \begin{array}{c|c|c}
  \mathbf{i}_\cC & \mathbf{j}_\cC & \mathbf{k}_\cC
  \end{array} \right]
  %
  \begin{bmatrix} x_\cC \\ y_\cC \\ z_\cC \end{bmatrix}
  %
  \end{aligned}
\end{equation}

In the end we arrive at the following formula.

:::puzzle
\begin{equation}
  \left[ \begin{array}{c} x_\cW \\ y_\cW \\ z_\cW \end{array} \right] =
    \underbrace{\overrightarrow{O_\cW O_\cC}}_{\mathbf{t}} +
  %
  \underbrace{
    \left[ \begin{array}{c|c|c}
    \mathbf{i}_\cC & \mathbf{j}_\cC & \mathbf{k}_\cC
    \end{array} \right]
  }_{\mathbf{R}}
  %
  \begin{bmatrix} x_\cC \\ y_\cC \\ z_\cC \end{bmatrix}
\end{equation}

We recognize the global rigid body motion $(\mathbf{R}, \mathbf{t})$
where:

- The translation vector $\mathbf{t}$ is the camera origin coordinates expressed
  in the world coordinate system.
- The rotation matrix $\mathbf{R}$ are the coordinates of the camera basis
  vectors expressed in the world coordinate system.
:::

In general, if this time we are to change from one coordinate
system $\cA$ ("camera") to another coordinate system $\cB$ ("world"), we can calculate
the rigid body motion as follows:

\begin{align}
  \mathbf{R}_{\cA \rightarrow \cB} &= \begin{bmatrix}
    \mathbf{i}_\cA \cdot \mathbf{i}_\cB &
    \mathbf{j}_\cA \cdot \mathbf{i}_\cB &
    \mathbf{k}_\cA \cdot \mathbf{i}_\cB \\
    %
    \mathbf{i}_\cA \cdot \mathbf{j}_\cB &
    \mathbf{j}_\cA \cdot \mathbf{j}_\cB &
    \mathbf{k}_\cA \cdot \mathbf{j}_\cB \\
    %
    \mathbf{i}_\cA \cdot \mathbf{k}_\cB &
    \mathbf{j}_\cA \cdot \mathbf{k}_\cB &
    \mathbf{k}_\cA \cdot \mathbf{k}_\cB \\
  \end{bmatrix} \\
  %
  \mathbf{t}_{\cA \rightarrow \cB} &= \begin{bmatrix}
    \overrightarrow{O_\cA O_\cB} \cdot \mathbf{i}_\cB \\
    \overrightarrow{O_\cA O_\cB} \cdot \mathbf{j}_\cB \\
    \overrightarrow{O_\cA O_\cB} \cdot \mathbf{k}_\cB
  \end{bmatrix}
\end{align}

These formula are interesting because it does not matter in which reference
coordinate system the two set of basis vectors are actually expressed.

One observation worth reminding for the remaining sections is the following proposition.

:::puzzle
```{proposition, name="Inverse Rotation"}
Let $\mathbf{R}$ be a rotation matrix in $\mathbb{R}^n$ for $n = 2$ or $n = 3$, its
inverse rotation matrix is calculated by transposition

\begin{equation}
  \mathbf{R}^{-1} = \mathbf{R}^T
\end{equation}
```
:::

# Euler Angles

In engineering, we like to decompose any 3D rotation into Euler angles as they
are quite intuitive to understand. The usual convention that is followed is
called the *Tait-Bryan* convention, which we describe as follows.

Specifically the Euler angles $(\psi, \theta, \phi)$ are the three
rotational quantities about each *intrinsic* axis which altogether describes the
3D rotation.

Let us first describe the rotation axes by visualizing an airplane. Consider its
local coordinate system that is fixed to this airplane. The usual axis
convention used in aerospace engineering is as follows:

- The $x$-axis is the longitudinal axis pointing to the airplane
  nose.
- The $y$-axis is the transversal axis pointing to the right.
- The $z$-axis is the vertical axis pointing downwards to the
  ground.

In terms of rotation,

- The $z$-axis is the (current) yaw axis (NO head movement)
- The $y$-axis is the (current) pich axis (YES head movement).
- The $x$-axis is the (current) roll axis ("Indian" MAYBE head movement).

A 3D rotation can be decomposed into three elementary rotations that must
composed in the following order:

1. Yaw about the $z$-axis of the airplane by an angle $\psi$,
2. Pitch about the **current** $y'$-axis of the airplane by an angle $\theta$,
3. Roll about the **current** $x''$-axis of the airplane by an angle $\phi$

Once again let us stress that the order to which we apply each elementary
rotation is very important.

## Formula of Elementary Rotations

Every now and then we may forget the formula of each elementary rotation and in
particular we do not remember their signs and orientations.

We can retrieve each coefficient of the matrix by reasoning about a small
positive quantity. A small angle will imply a small change, and then a cosine
close to 1 and a sine close to 0. By visualization, we can determine the sign of
each coefficient.

- When the airplane is yawing positively, it is steering to the right as the
  $x$-axis is rotating towards the $y$-axis:

  :::puzzle
  \begin{equation}
    \mathbf{R}_z(\psi) = \left[ \begin{array}{ccc}
      \cos\psi & -\sin\psi & 0 \\
      \sin\psi &  \cos\psi & 0 \\
             0 &         0 & 1 \\
    \end{array} \right]
  \end{equation}
  :::

- When the airplane is pitching positively, its nose is looking up as the
  $z$-axis is rotating towards the $x$-axis.

  :::puzzle
  \begin{equation}
    \mathbf{R}_y(\theta) = \left[ \begin{array}{ccc}
      \cos\theta & 0 & \sin \theta \\
               0 & 1 &           0 \\
     -\sin\theta & 0 & \cos \theta \\
    \end{array} \right]
  \end{equation}
  :::

- When the airplane is rolling positively, it right wing is tilting down as the
  $y$-axis is rotating towards the $z$-axis.

  :::puzzle
  \begin{equation}
    \mathbf{R}_x (\phi) = \left[ \begin{array}{ccc}
      1 &        0 &         0 \\
      0 & \cos\phi & -\sin\phi \\
      0 & \sin\phi &  \cos\phi \\
    \end{array} \right]
  \end{equation}
  :::

## Composite Euler Rotation

The rotation matrix expressed with respect to the *extrinsic* axes (i.e., the
axes of the original local coordinates before rotating the airplane) is
calculated as follows.

:::puzzle
```{proposition, name="Composite Euler Rotation"}
The composite Euler rotation parameterized by $(\psi, \theta, \phi)$ is
calculated as

\begin{equation}
  \mathbf{R} (\psi, \theta, \phi) = \mathbf{R}_z (\psi)
                                    \mathbf{R}_y (\theta)
                                    \mathbf{R}_x (\phi)
\end{equation}
```
:::

This nice visualisation tool can be useful to check our understanding:
http://danceswithcode.net/engineeringnotes/rotations_in_3d/demo3D/rotations_in_3d_tool.html

```{proof}
It is useful to provide a proof that justifies the Euler decomposition we have
exhibited above.

In terms of matrix multiplication, the composite rotation is

\begin{equation}
  \mathbf{\mathbf{R}} (\psi, \theta, \phi) = \mathbf{R}_{x''} (\phi)
                                             \mathbf{R}_{y'} (\theta)
                                             \mathbf{R}_{z} (\psi)
\end{equation}

In the sequel, we will alleviate the notation by omitting the angles.

To obtain $\mathbf{R}_{y'}$, we need to understand that the pitch rotation
is done about the current axis $\mathbf{y}' = \mathbf{R}_z \mathbf{y}$.
And the vector $\mathbf{y}'$ is the coordinates of the current airplane $y'$-axis
w.r.t. the original axes.

Now we denote

- the basis vectors of the original local coordinate system by
  $(\mathbf{i}, \mathbf{j}, \mathbf{k})$ and
- the basis vectors of the current local coordinate system by
  $(\mathbf{i}', \mathbf{j}', \mathbf{k}')$.

In the sequel, we will alleviate the notation by omitting the origin $O$
of the coordinate systems because there is no translation.

We can see that the intrinsic pitch rotation matrix expressed in the *current*
local coordinate system $(x', y', z')$ has the convenient form:

\begin{equation}
  \mathbf{R}_y = \left[ \begin{array}{ccc}
    \cos\theta & 0 & \sin \theta \\
             0 & 1 &           0 \\
   -\sin\theta & 0 & \cos \theta \\
  \end{array} \right]
\end{equation}

But we want the rotation matrix $\mathbf{R}_{y'}$ to be expressed in the
*original* coordinate system $(x, y, z)$.  So how do we get it?

As we can see above, the key point to understand is that to go from the current
coordinates $\mathbf{u}'$ to the original coordinates $\mathbf{u}$,
we need to multiply the current coordinates $\mathbf{u}'$ with the
rotation $\mathbf{R}_z$, which "adds" the necessary angles offsets.

Let us detail this point to convince ourselves.

- In the current local coordinate system $(x', y', z')$, the coordinates
  of the basis vectors $(\mathbf{i}', \mathbf{j}', \mathbf{k}')$ are
  simply the column vectors $\mathbf{e}^i$ of the identity matrix
  $\mathbf{I}_3$.
- In the original local coordinate system $(x, y, z)$, the coordinates of
  the same basis vectors $(\mathbf{i}', \mathbf{j}', \mathbf{k}')$ are
  precisely the column vectors $\mathbf{R}_z^i$ of the rotation matrix
  $\mathbf{R}_z$.

Now consider any point $u$ of the airplane, if its
coordinates are $\mathbf{u}'$ in the current coordinate system $(x',
y', z')$, then by linear combination

\begin{equation}
  \mathbf{u}' = u_i' \mathbf{e}^i \ \text{(using Einstein's notation)}
\end{equation}

Then its coordinates in the the original local coordinate system $(x, y,
z)$ are

\begin{equation}
  \mathbf{u} = u_i' \mathbf{R}_z^i \\
\end{equation}

And thus we recognize the matrix-vector multiplication

\begin{equation}
  \mathbf{u} = \mathbf{R}_z \mathbf{u}'
\end{equation}

If we rotate the point $u$ by $\mathbf{R}_{y'}$, we create a second
point $v$ where:

- In the current coordinate system $(x', y', z')$, its coordinates are
  simply

  \begin{equation}
    \mathbf{v}' = \mathbf{R}_y \mathbf{u}'
  \end{equation}

- In the original coordinate system $(x, y, z)$, its coordinates are
  $\mathbf{v}$, thus by injecting the inverse rotation on both sides of
  the equality

  \begin{align*}
    (\mathbf{R}_z^T \mathbf{v}) &= \mathbf{R}_y\ (\mathbf{R}_z^T \mathbf{u})  \\
    \mathbf{v} &= \mathbf{R}_z \mathbf{R}_y \mathbf{R}_z^T\ \mathbf{u}
  \end{align*}

We have just calculated the pitch rotation in the original coordinate system:

\begin{equation}
  \mathbf{R}_{y'} = \mathbf{R}_{z}
                    \mathbf{R}_{y}
                    \mathbf{R}_{z}^T
\end{equation}

Likewise the rotation $\mathbf{R}_{x''}$ is obtained as:

\begin{equation}
  \mathbf{R}_{x''} = \mathbf{R} \mathbf{R}_{x} \mathbf{R}^T
\end{equation}

where

\begin{equation}
  \mathbf{R} = \mathbf{R}_z \mathbf{R}_{y}
\end{equation}

And thus

\begin{equation}
  \mathbf{R}_{x''} = \mathbf{R}_z \mathbf{R}_y \mathbf{R}_{x} \mathbf{R}_y^T \mathbf{R}_z^T
\end{equation}

By multiplying the three rotations, the inverse rotations will disappear and we get
the formula as exposed in the Wikipedia page about Euler angles.
```
