if (MSVC)
  do_step_message("Found MSVC compiler:")
  add_definitions(-D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE)
  message(STATUS "  - NON-SECURE warnings are disabled.")
  add_definitions(/EHsc)
  message(STATUS "  - Exception handling activated.")
  if (MSVC_VERSION EQUAL 1700)
    message(STATUS "  - Using version 2012: setting '_VARIADIC_MAX=10' to compile 'Google Test'")
    add_definitions(/D _VARIADIC_MAX=10)
  endif ()
endif (MSVC)

if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  do_step_message("Found ${CMAKE_CXX_COMPILER_ID} compiler:")
  set (ENABLE_CXX11 "-std=c++11")
  if (CMAKE_COMPILER_IS_GNUCXX)
    execute_process(COMMAND "${CMAKE_CXX_COMPILER} -dumpversion"
      OUTPUT_VARIABLE GCC_VERSION)
    if (GCC_VERSION VERSION_LESS 4.7)
      set(ENABLE_CXX11 "-std=c++0x")
    endif ()
  endif ()
  set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ENABLE_CXX11}")
  message(STATUS "  - Activating C++11 features, specifically for dependencies with Boost libraries.")
  message(STATUS "  - C++11 compiler flags: ${CMAKE_CXX_FLAGS}")
endif ()
