include_directories(${Eigen3_DIR} ${DO_INCLUDE_DIR})

if (DO_USE_FROM_SOURCE)
  get_property(DO_ImageIO_ADDED GLOBAL PROPERTY _DO_ImageIO_INCLUDED)
  if (NOT DO_ImageIO_ADDED)
    do_glob_directory(${DO_SOURCE_DIR}/ImageIO)
    do_create_common_variables("ImageIO")
    do_generate_library("ImageIO")
  endif ()
endif ()