include_directories(${Eigen3_DIR} ${DO_INCLUDE_DIR})

if (DO_USE_FROM_SOURCE)
  get_property(DO_Core_ADDED GLOBAL PROPERTY _DO_Core_INCLUDED)
  if (NOT DO_Core_ADDED)
    do_create_common_variables("Core")
    do_glob_directory(${DO_SOURCE_DIR}/Core)
    do_generate_library("Core")
  endif ()
endif ()