sara_include_modules("Core;Geometry;Graphics")

if (SARA_USE_FROM_SOURCE)
  get_property(DO_Sara_Features_ADDED GLOBAL PROPERTY _DO_Sara_Features_INCLUDED)
  if (NOT DO_Sara_Features_ADDED)
    sara_glob_directory(${DO_Sara_SOURCE_DIR}/Features)
    sara_create_common_variables("Features")
    sara_set_internal_dependencies("Features" "Graphics")
    sara_generate_library("Features")
  endif ()
endif ()
