if (SARA_USE_FROM_SOURCE)
  get_property(DO_Sara_Geometry_ADDED GLOBAL PROPERTY _DO_Sara_Geometry_INCLUDED)
  if (NOT DO_Sara_Geometry_ADDED)
    sara_glob_directory(${DO_Sara_SOURCE_DIR}/Geometry)
    sara_create_common_variables("Geometry")
    sara_set_internal_dependencies("Geometry" "Core")
    sara_generate_library("Geometry")
  endif ()
endif ()
