if (SARA_USE_FROM_SOURCE)
  get_property(DO_Sara_Visualization_ADDED GLOBAL PROPERTY _DO_Sara_Visualization_INCLUDED)
  if (NOT DO_Sara_Visualization_ADDED)
    sara_glob_directory(${DO_Sara_SOURCE_DIR}/Visualization)
    sara_create_common_variables("Visualization")
    sara_set_internal_dependencies("Visualization" "Core;Graphics;Features;Match")
    sara_generate_library("Visualization")
  endif()
endif ()
