name: Continuous Integration

on:
  push:
  pull_request:
  release:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # The build machine is very slow and dealing with the CI is
        # time-consuming.
        #
        # It may not be worth sticking rigorously to build and test on these
        # platforms.
        # os:  [macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            container: 'oddkiva/sara-devel:cuda12.1.0-ubuntu22.04-trt8.6-swift5.9.1-halide16.0.0'
          - os: ubuntu-latest
            container: 'oddkiva/sara-emsdk-devel:latest'

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4

    # TODO: figure out howto save and reuse the ccache folder.

    - name: Build and test on Ubuntu
      if: startsWith(matrix.container, 'oddkiva/sara-devel')
      run: |
        git config --global --add safe.directory $(pwd)
        ./build.py --tasks library --build_type Release --from_scratch --ci

    - name: Build and test WASM on Ubuntu
      if: startsWith(matrix.container, 'oddkiva/sara-emsdk-devel')
      run: |
        git config --global --add safe.directory $(pwd)
        ./build.py --tasks web --build_type Release --from_scratch

    # - name: Run code coverage
    #   run:|
    #     make -j$(nproc) coverage
    #
    # - name: Send code coverage to Coveralls
    #   if: startsWith(matrix.config.name, 'Ubuntu 22.04')
    #   run: |
    #     cd /home/runner/work/sara/sara
    #     lcov --compat-libtool --directory build --base-directory=cpp/src --capture --output-file=coverage.info
    #     lcov --remove coverage.info '/usr/*' --output-file coverage.info
    #     lcov --remove coverage.info '/home/runner/work/sara/sara/cpp/third-party/*' --output-file coverage.info
    #     lcov --remove coverage.info '/home/runner/work/sara/sara/cpp/test/*' --output-file coverage.info
    #     lcov --remove coverage.info '/home/runner/work/sara/sara/build/*' --output-file coverage.info
    #     coveralls-lcov coverage.info
